server:
  compression:
    enabled: true
    mime-types: application/json,text/html,text/css,application/javascript
  port: ${port:8080}
  http2:
    enabled: false
spring:
  main:
    allow-circular-references: true
  datasource:
    url: ${db.url:jdbc:sqlserver://serverName\\instanceName:port;databaseName=SAMPLE_DB;integratedSecurity=true;}
    username: ${db.app.username:APP_admin}
    password: ${db.app.password:APP_admin_password}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: SamplePool
      max-lifetime: 60000
      connection-init-sql: SELECT 1
      connection-timeout: ${db.hikari.connection_timeout:30000}
      idle-timeout: ${db.hikari.idle_timeout:600000}
      leak-detection-threshold: ${db.hikari.leak_detection_threshold:15000}
      maximum-pool-size: ${db.hikari.maximum_pool_size:10}
  jackson:
    serialization:
      write-dates-as-timestamps: true
  jpa:
    properties:
      hibernate:
        max_fetch_depth: 3
        default_batch_fetch_size: 25
        dialect_resolvers: com.cicad.app.common.DatabaseDialectResolver
        default_schema: ${db.schema:APP}
    database-platform:
  liquibase:
    user: ${db.app.username:APP_admin}
    password: ${db.app.password:APP_admin_password}
    url: ${db.url:jdbc:sqlserver://serverName\\instanceName:port;databaseName=SAMPLE_DB;integratedSecurity=true;}
    change-log: classpath:db/changelog/db.changelog-master.yml
    default-schema: ${db.schema:APP}
